# This is the configuration used to check the rubocop source code.

# inherit_gem:
#   deka_eiwakun: 'config/rubocop.yml'

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.1

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top level class documentation comment.
Style/Documentation:
  Enabled: false

Metrix/LineLength:
  Enabled: false

Style/IndentHeredoc:
  EnforcedStyle: powerpack

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
