abbr --add g "git"
abbr --add be 'bundle exec'
abbr --add r "bin/rails"
alias e 'emacsclient -n -c -a ""'
alias e-kill 'emacsclient -e "(kill-emacs)"'
abbr --add psg 'ps aux | grep -v grep | grep'
alias onkeyboard "sudo kextload /System/Library/Extensions/AppleUSBTopCase.kext/Contents/PlugIns/AppleUSBTCKeyboard.kext/"
alias offkeyboard "sudo kextunload /System/Library/Extensions/AppleUSBTopCase.kext/Contents/PlugIns/AppleUSBTCKeyboard.kext/"
abbr --add ghc "stack ghc --"
abbr --add ghci "stack ghci"
abbr --add runghc "stack runghc --"
abbr --add runhaskell "stack runghc --"
abbr --add s "stack"
abbr --add sb "stack build"
abbr --add si "stack install"
abbr --add se "stack exec"
abbr --add cat "bat"
alias chrome "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
abbr --add dc "docker-compose"
abbr --add ls "exa"
abbr --add la "exa -al"
abbr --add ll "exa -l"
abbr --add tree "exa -T"
abbr --add dcr "docker-compose run --rm \$APP_NAME"
abbr --add dce "docker-compose exec \$APP_NAME"
abbr --add mkdir "mkdir -p -v"
abbr --add c "cargo"
abbr --add ch "cargo check"
abbr --add cr "cargo run"
abbr --add ct "cargo test"
abbr --add codegh "ghq list | peco | xargs -I{} code (ghq root)/{}"
abbr --add jman "LANG=ja_JP.UTF-8 man"
