;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-M-x
        paredit-forward-delete
        paredit-forward-kill-word
        scroll-other-window
        ))

(setq mc/cmds-to-run-once
      '(
        org-self-insert-command
        ruby-electric-delete-backward-char
        ))
